CREATE TABLE books (
  id SERIAL PRIMARY KEY,
  isbn VARCHAR NOT NULL UNIQUE,
  title VARCHAR NOT NULL,
  author VARCHAR NOT NULL,
  year INTEGER NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  username VARCHAR NOT NULL UNIQUE,
  email VARCHAR NOT NULL UNIQUE,
  age INTEGER DEFAULT -1,
  hash VARCHAR NOT NULL
);


CREATE TABLE reviews (
  id SERIAL PRIMARY KEY,
  bookid INTEGER NOT NULL,
  userid INTEGER NOT NULL,
  posted DATE NOT NULL DEFAULT CURRENT_DATE,
  review VARCHAR NOT NULL,
  rating INTEGER NOT NULL CHECK (rating > 0 AND rating < 6),
  CONSTRAINT UC_reviews UNIQUE (bookid, userid)
);
